name: Node.js CI/CD

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 18] # Specify the Node.js versions you want to test

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }} # Use the matrix variable

    # Install dependencies and build
    - name: Install dependencies
      run: |
        npm install
        npm run build # If your project requires a build step

    # Deploy to Azure App Service
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gitget170705' # Replace with your Azure App Service name
        slot-name: 'production' # Optional, use if deploying to a specific slot
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Store your Azure publish profile in GitHub Secrets
      
      env:
        NODE_ENV: production
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
        GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
        MONGODBURI: ${{ secrets.MONGODBURI }}